server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: store
  data:
    mongodb:
      uri: mongodb://localhost:27017/store?readPreference=primary&appname=store_app&directConnection=true&ssl=false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka